export type Customer = {
  id: number;
  customerid: number | null;
  firstname: string | null;
  middlename: string | null;
  lastname: string | null;
  customertype: string | null;
  accountno: string | null;
  accountclosedate: string | null;
  dateofbirth: string | null;
  addressres: string | null;
  areares: string | null;
  telephoneres: string | null;
  addressoffice: string | null;
  areaoffice: string | null;
  telephoneoffice: string | null;
  telephoneext: string | null;
  fax: string | null;
  email: string | null;
  weburl: string | null;
  datefirstcontacted: string | null;
  paymentmode: string | null;
  deliverydate: string | null;
  deliveryarea: string | null;
  reqbottles: number | null;
  requirement: string | null;
  notes: string | null;
  modifydate: string | null;
  modifybyuser: number | null;
  isdeleted: boolean | null;
  depositamount: number | null;
  isdepositvoucherdone: boolean | null;
  rate_per_bottle: number | null;
  delivery_person: number | null;
  istaxable: boolean | null;
  gender: string | null;
  tax: number | null;
};
